[mert]
salt = "YPLc2WWEI8mxGa+4cmtqHxtfFaMNzPZz0OvLRw6EOFka0Hp+MRa0kDg9lXc7YRfs+uSIH8WyA5xfcC7uRemy3g=="
accessibility = ["denis"]
hash = "b8ldj4uQtIBeDcRPvrCu9xRX7aYsBcEHHSpj4f1pAWRHZ8GZhC+93zy+dw1YSbB3v4p0WqkydHAYnabuJKBa+Q=="
unix = 1733571984
group = "mert"
