[mert]
salt = "bzZODbJj091wL73WKoxzQRTuf58ezKnUP57VWLoz6QtwRkCkDtNYudoENpozC/iAx18QCutEv92hV91oE5wKeQ=="
access = "LvnUtsXoBvnZmUzAwJMttW56JE41fIwEm9PQngIGGXa0V/pfiUUONT24+7mFbdR0S4yd+lAFtR0tmloY7mt0GQ=="
accessibility = ["denis"]
hash = "qjyhFmyIrL0sAfNWgUz/oazW/KzvsPrEi9qnDu8hGNPqH3CgdSaCHXR1j8O+unfiE7iqB875whjzvb9QkDNMYg=="
unix = 1733917042
group = "mert"
