[mert]
salt = "Vje5pKQGx6xLsj6qSgYz+xkNlz2bxeKRFIFAcvcVdOIZRzPdOZIQl5hH7OxlzcGoAWIdmAG3mlgstw+EFDezZQ=="
accessibility = ["denis"]
pwd = "XhLzRVsyefDTo7XTzrBOkQ=="
hash = "XYgTRz5zJ9rczKxv/J5Rkwphi4qn0KIEbZaFzZUhNJKA9QQzQlQOo7nV9gtCxnAYXOfaacR/TGKxVZ95nVdkBQ=="
unix = 1733849812
group = "mert"
