# Host
ddb-port=5142
ddb-address=localhost

# Denis
# Leave empty to generate a secure token on first start.
ddb-main-token=

# Options
language=auto
max-token-size=5
send-client-actions=true
use-delogg=false
start-with-details=false

# Loggers
mac-address=true

# Security
max-connections-per-ip=12
use-token=true
change-token-on-every-new-client-session=true
ask-token-on-every-new-client-session=true
